name: Build & Push Container
description: Builds a container from a Dockerfile and pushes to registry

inputs:
  context:
    description: Effective Working Directory
    required: true
    default: "./"
  image_name:
    description: Image Name
    required: true
  image_tags:
    description: Tags for the Image
    required: false
  image_registry:
    description: Image Repository
    required: true
  image_registry_user: 
    description: Image Registry User
    required: true
  image_registry_password:
    description: Image Registry User Password
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Determine image tags
    #   shell: bash
    #   if: inputs.image_tags == ''
    #   run: |
    #     echo "image_tags=latest ${GITHUB_SHA::12}" | tee -a $GITHUB_ENV

    # https://github.com/docker/metadata-action#readme
    - name: Prepare Container Metadata tags
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.image_registry }}/${{ inputs.image_name }}
        flavor: |
          latest=true
        tags: |
          type=sha
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    # https://github.com/docker/login-action#readme
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.image_registry }}
        username: ${{ inputs.image_registry_user }}
        password: ${{ inputs.image_registry_password }} 

    # https://github.com/docker/build-push-action#readme
    - name: Build and Push to Registry
      id: builder
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
