kind: Template
apiVersion: template.openshift.io/v1
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        deployment: $***REMOVED***NAME***REMOVED***
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      labels:
        app: $***REMOVED***NAME***REMOVED***
        app.kubernetes.io/component: $***REMOVED***NAME***REMOVED***
        app.kubernetes.io/instance: $***REMOVED***NAME***REMOVED***
      name: $***REMOVED***NAME***REMOVED***
      namespace: $***REMOVED***DEPLOY_NAMESPACE***REMOVED***
  - apiVersion: apps/v1
    kind: Deployment
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          deployment: $***REMOVED***NAME***REMOVED***
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftNewApp
          creationTimestamp: null
          labels:
            deployment: $***REMOVED***NAME***REMOVED***
        spec:
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/$***REMOVED***IMAGE_NAMESPACE***REMOVED***/$***REMOVED***IMAGE_NAME***REMOVED***:$***REMOVED***IMAGE_TAG***REMOVED***
              imagePullPolicy: IfNotPresent
              name: $***REMOVED***NAME***REMOVED***
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
              volumeMounts:
              - name: config-volume
                mountPath: /opt/app-root/src/config
              resources: ***REMOVED******REMOVED***
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          volumes:
          - name: config-volume
            configMap:
              defaultMode: 420
              name: $***REMOVED***NAME***REMOVED***-config
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: ***REMOVED******REMOVED***
          terminationGracePeriodSeconds: 30
    metadata:
      annotations:
        deployment.kubernetes.io/revision: '2'
        image.openshift.io/triggers: >-
          [***REMOVED***"from":***REMOVED***"kind":"ImageStreamTag","name":"$***REMOVED***IMAGE_NAME***REMOVED***:$***REMOVED***IMAGE_TAG***REMOVED***","namespace":"$***REMOVED***IMAGE_NAMESPACE***REMOVED***"***REMOVED***,"fieldPath":"spec.template.spec.containers[?(@.name==\"$***REMOVED***IMAGE_NAME***REMOVED***\")].image"***REMOVED***]
        openshift.io/generated-by: OpenShiftNewApp
      generation: 2
      labels:
        app: $***REMOVED***NAME***REMOVED***
        app.kubernetes.io/component: $***REMOVED***NAME***REMOVED***
        app.kubernetes.io/instance: $***REMOVED***NAME***REMOVED***
      name: $***REMOVED***NAME***REMOVED***
      namespace: $***REMOVED***DEPLOY_NAMESPACE***REMOVED***
  - apiVersion: v1
    data:
      __ENV.js: >-
        window.__ENV = ***REMOVED***
          NODE_ENV: 'production',
          REACT_APP_APP_DOMAIN: '$***REMOVED***BASE_GATEWAY_URL***REMOVED***/exitsurveyadmin$***REMOVED***DEPLOY_ENV***REMOVED***/',
          REACT_APP_API_DOMAIN: '$***REMOVED***BASE_GATEWAY_URL***REMOVED***/exitsurveyadmin-api$***REMOVED***DEPLOY_ENV***REMOVED***',
          REACT_APP_APP_PATH: '/',
          REACT_APP_AUTH_SCOPE: 'profile',
          REACT_APP_AUTH_URL: '$***REMOVED***KEYCLOAK_URL***REMOVED***',
          REACT_APP_AUTH_REALM: 'standard',
          REACT_APP_AUTH_ROLE: '$***REMOVED***KEYCLOAK_ROLE***REMOVED***',
          REACT_APP_AUTH_CLIENT_ID: '$***REMOVED***KEYCLOAK_CLIENT_ID***REMOVED***',
      ***REMOVED***
    kind: ConfigMap
    metadata:
      labels:
        app: $***REMOVED***NAME***REMOVED***
      name: $***REMOVED***NAME***REMOVED***-config
      namespace: $***REMOVED***DEPLOY_NAMESPACE***REMOVED***
parameters:
- name: IMAGE_NAMESPACE
  required: true
  description: The namespace holding the image to deploy from
- name: IMAGE_TAG
  required: true
  description: The output image stream tag
- name: IMAGE_NAME
  required: true
  description: The name of the image (likely the same as the NAME param)
- name: DEPLOY_NAMESPACE
  required: true
  description: The namespace in which to deploy
- name: NAME
  required: true
  description: The name of the deployment, e.g. esa
- name: API_NAME
  required: true
  description: The name of the API deployment, e.g. esa-api
- name: KEYCLOAK_URL
  required: true
  description: The URL to the Keycloak server to auth against
- name: KEYCLOAK_CLIENT_ID
  required: true
  description: The client ID on Keycloak
- name: KEYCLOAK_ROLE
  required: true
  description: The Keycloak role required
- name: BASE_OPENSHIFT_URL
  required: true
  description: The base URL for Openshift
- name: BASE_GATEWAY_URL
  required: true
  description: The base Gateway URL
- name: DEPLOY_ENV
  required: true
  description: The lifecycle environment
