// <auto-generated />
using System;
using ExitSurveyAdmin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExitSurveyAdmin.Migrations
***REMOVED***
    [DbContext(typeof(ExitSurveyAdminContext))]
    [Migration("20191209201953_InitialCreate")]
    partial class InitialCreate
    ***REMOVED***
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        ***REMOVED***
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("ExitSurveyAdmin.Models.Employee", b =>
                ***REMOVED***
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Employees");
              ***REMOVED***);
#pragma warning restore 612, 618
      ***REMOVED***
  ***REMOVED***
***REMOVED***
