name: Pull Request Opened
permissions:
  contents: read
  id-token: write

env:
  APP_NAME: esa
  API_NAME: esa-api

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
  pull_request:
    branches:
    - dev
    - master
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'charts/**'

jobs:
  build-frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push
        uses: ./.github/actions/build-push-container
        with:
          context: ./frontend
          image_name: ${{ env.APP_NAME }}
          image_registry: ${{ secrets.IMAGE_REGISTRY }}
          image_registry_user: ${{ secrets.IMAGE_REGISTRY_USER }}
          image_registry_password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
          vite_app_path: ${{ secrets.VITE_APP_PATH }}

  build-api:
    name: Build & Push Backend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build & Push
        uses: ./.github/actions/build-push-container
        with:
          context: ./backend
          image_name: ${{ env.API_NAME }}
          image_registry: ${{ secrets.IMAGE_REGISTRY }}
          image_registry_user: ${{ secrets.IMAGE_REGISTRY_USER }}
          image_registry_password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}